using UnityEngine;
using Photon.Pun;

/// <summary>State machine for the two-QR automatic calibration flow.</summary>
public enum DualQRCalibState { NeedsA, NeedsB, Complete }

public class MeshHandler : MonoBehaviourPun
{
    [Header("Scene内の事前配置メッシュのオブジェクト名")]
    [SerializeField] private string meshObjectName = "SharedMesh";

    [Header("Calibration Settings")]
    [SerializeField] private float moveSpeed = 1.0f;
    [SerializeField] private float rotateSpeed = 45f;

    [Header("Android Collision Mesh Simplification")]
    [Tooltip("Pre-baked simplified meshes generated by CoGaze → Bake Collision Mesh. Assign to skip runtime simplification.")]
    [SerializeField] private Mesh[] bakedCollisionMeshes;
    [Tooltip("QEM quality for Bake (0=最小ポリゴン, 1=原型維持). 0.02〜0.05 が衝突判定用として推奨。")]
    [Range(0f, 1f)]
    [SerializeField] private float collisionMeshQuality = 0.03f;

    [Header("Single-QR Calibration (legacy; overridden when both Dual-QR indicators are assigned)")]
    [Tooltip("QRコードのmarkerId がこの文字列で始まる場合、メッシュの初期位置として自動セットする。例: 'QR_CALIB'")]
    [SerializeField] private string calibrationQRPrefix = "QR_CALIB";
    [Tooltip("QR検出時にこのTransformがQR位置へ来るようメッシュを移動する。未設定時はSharedMesh原点をQR位置に合わせる。")]
    [SerializeField] private Transform calibrationAnchor;

    [Header("Dual-QR Calibration (active when both indicatorA and indicatorB are assigned)")]
    [Tooltip("QR-A の markerId（例: 'QR_CALIB_A'）。indicatorA/B が両方設定されている場合に使用。")]
    [SerializeField] private string calibrationQRIdA = "QR_CALIB_A";
    [Tooltip("QR-B の markerId（例: 'QR_CALIB_B'）。")]
    [SerializeField] private string calibrationQRIdB = "QR_CALIB_B";
    [Tooltip("SharedMesh の子として置いたQR-A位置インジケーター Transform。")]
    [SerializeField] private Transform indicatorA;
    [Tooltip("SharedMesh の子として置いたQR-B位置インジケーター Transform。")]
    [SerializeField] private Transform indicatorB;

    private GameObject meshObject;
    private bool _qrCalibrated = false;
    private QRSpatialManager _qrManager;

    // ── Dual-QR state ─────────────────────────────────────────────────────
    private DualQRCalibState _dualCalibState = DualQRCalibState.NeedsA;
    private Vector3?         _detectedA;
    private Vector3?         _detectedB;

    /// <summary>true when both indicatorA and indicatorB are assigned — uses 2-QR alignment.</summary>
    public bool             IsDualQRMode          => indicatorA != null && indicatorB != null;
    /// <summary>Current step of the dual-QR calibration state machine.</summary>
    public DualQRCalibState CurrentDualCalibState => _dualCalibState;

    /// <summary>Fired on the Worker when calibration mode is toggled on (true) or off (false).</summary>
    public event System.Action<bool>            OnCalibrationChanged;
    /// <summary>Fired on the Worker when calibration is confirmed (A button).</summary>
    public event System.Action                  OnCalibrationConfirmed;
    /// <summary>Fired on the Worker at each dual-QR calibration step (NeedsA → NeedsB → Complete).</summary>
    public event System.Action<DualQRCalibState> OnDualQRCalibStep;
    /// <summary>Fired on ALL clients via RPC when dual-QR calibration completes.</summary>
    public event System.Action                   OnCalibCompleteNotified;

    private void Start()
    {
        meshObject = GameObject.Find(meshObjectName);
        if (meshObject == null)
        {
            Debug.LogWarning($"[MeshHandler] Pre-placed mesh '{meshObjectName}' not found in scene.");
            return;
        }
        OptimizeMeshPerformance(meshObject);
#if UNITY_ANDROID && !UNITY_EDITOR
        // Default hidden on Quest — photogrammetry mesh far exceeds Quest GPU budget.
        // Use X button to show during calibration, then hide again.
        foreach (var r in meshObject.GetComponentsInChildren<MeshRenderer>(true))
            r.enabled = false;

        _qrManager = FindAnyObjectByType<QRSpatialManager>();
        if (_qrManager != null)
            _qrManager.OnMarkerDetected += OnQRMarkerDetected;
        else
            Debug.LogWarning("[MeshHandler] QRSpatialManager not found — QR calibration disabled.");
#endif
    }

    private void OnDestroy()
    {
#if UNITY_ANDROID && !UNITY_EDITOR
        if (_qrManager != null)
            _qrManager.OnMarkerDetected -= OnQRMarkerDetected;
#endif
    }

    private void OptimizeMeshPerformance(GameObject target)
    {
        foreach (var r in target.GetComponentsInChildren<MeshRenderer>(true))
        {
            r.shadowCastingMode = UnityEngine.Rendering.ShadowCastingMode.Off;
            r.receiveShadows = false;
        }

        // MeshColliders are required on Quest — GazeVisualizer raycasts against them to place
        // the Circle marker. On Android we replace each collider mesh with a vertex-clustered
        // simplification so bake time and raycast cost stay within Quest's budget.
        int added = 0;
        foreach (var f in target.GetComponentsInChildren<MeshFilter>(true))
        {
            if (f.GetComponent<Collider>() == null)
            {
                f.gameObject.AddComponent<MeshCollider>();
                added++;
            }
        }
        if (added > 0) Debug.Log($"[MeshHandler] Added {added} MeshColliders.");

#if UNITY_ANDROID && !UNITY_EDITOR
        if (bakedCollisionMeshes != null && bakedCollisionMeshes.Length > 0)
            ApplyBakedCollisionMeshes(target);
        else
        {
            Debug.LogWarning("[MeshHandler] No baked collision mesh assigned. Run CoGaze → Bake Collision Mesh before building to Quest.");
        }
#endif

        var colliders = target.GetComponentsInChildren<MeshCollider>(true);
        if (colliders.Length > 0 && target.GetComponent<Rigidbody>() == null)
        {
            var rb = target.AddComponent<Rigidbody>();
            rb.isKinematic = true;
            rb.useGravity = false;
        }
    }

    private void Update()
    {
        if (!photonView.IsMine || meshObject == null) return;
#if UNITY_ANDROID
        UpdateCalibration();
#endif
    }

#if UNITY_ANDROID
    // Analog axis threshold — handles Touch Plus axis inconsistency on MQ3 / MQ3S.
    private const float TriggerThreshold = 0.7f;
    private const float StickDeadzone    = 0.15f;

    // Grip rising-edge state for toggle detection
    private bool _gripWasDown = false;

    // ── Manual calibration: active ONLY while the left X button is HELD ──────
    // The default grip stays free for "QR found" (SetupCoordinator registration / IdentificationTask
    // completion); holding X is the deliberate gesture to calibrate, so the mesh is never moved by
    // accident during the experiment.
    private bool         _calibActive      = false; // left X held
    private bool         _grabbing         = false; // right grip held → mesh follows the hand
    private Vector3      _grabOffset;                // mesh − controller at grab start
    private float        _calibSendTimer   = 0f;     // throttle live position broadcasts
    private OVRCameraRig _ovrRig;
    private const float  CalibSendInterval = 2.5f;   // seconds between position sends while calibrating

    private void UpdateCalibration()
    {
        // Mesh calibration is gated behind HOLDING the left X button. The default grip stays free for
        // "QR found" (SetupCoordinator registration / IdentificationTask completion), so the mesh is
        // never moved by accident during the experiment.
        bool xHeld = OVRInput.Get(OVRInput.Button.One, OVRInput.Controller.LTouch);

        if (xHeld != _calibActive)
        {
            _calibActive = xHeld;
            OnCalibrationChanged?.Invoke(_calibActive);
            SetMeshRenderersVisible(_calibActive);   // show the mesh while calibrating, hide on exit
            if (_calibActive)
            {
                _calibSendTimer = 0f;
            }
            else
            {
                // Exit: stop the haptic, drop any grab, and push the final pose to everyone.
                _grabbing    = false;
                _gripWasDown = false;
                OVRInput.SetControllerVibration(0f, 0f, OVRInput.Controller.LTouch);
                SendMeshTransform();
                photonView.RPC(nameof(RPC_NotifyCalibComplete), RpcTarget.AllBuffered);
                _qrManager?.ResyncAllMarkers();
                OnCalibrationConfirmed?.Invoke();
                Debug.Log("[MeshHandler] Manual calibration ended — final pose sent.");
            }
        }

        if (!_calibActive) return;

        // Gentle continuous vibration on the X hand signals that calibration is active.
        OVRInput.SetControllerVibration(0.3f, 0.3f, OVRInput.Controller.LTouch);

        // Right grip = grab the mesh; while held it follows the right controller (move / push / pull).
        float   grip     = OVRInput.Get(OVRInput.Axis1D.PrimaryHandTrigger, OVRInput.Controller.RTouch);
        bool    gripDown = grip > TriggerThreshold;
        Vector3 ctrl     = RightControllerWorldPos();
        if (gripDown && !_gripWasDown)
        {
            _grabbing   = true;
            _grabOffset = meshObject.transform.position - ctrl;   // preserve the mesh's offset from the hand
        }
        if (gripDown && _grabbing)
            meshObject.transform.position = ctrl + _grabOffset;
        if (!gripDown) _grabbing = false;
        _gripWasDown = gripDown;

        // Right stick X = yaw rotation around world-up.
        Vector2 stick = OVRInput.Get(OVRInput.Axis2D.PrimaryThumbstick, OVRInput.Controller.RTouch);
        if (Mathf.Abs(stick.x) > StickDeadzone)
            meshObject.transform.Rotate(Vector3.up, stick.x * rotateSpeed * Time.deltaTime, Space.World);

        // Broadcast the in-progress pose every few seconds so the Expert sees it move live.
        _calibSendTimer += Time.deltaTime;
        if (_calibSendTimer >= CalibSendInterval)
        {
            _calibSendTimer = 0f;
            SendMeshTransform();
        }
    }

    private Vector3 RightControllerWorldPos()
    {
        if (_ovrRig == null) _ovrRig = FindAnyObjectByType<OVRCameraRig>();
        if (_ovrRig != null) return _ovrRig.rightHandAnchor.position;
        return OVRInput.GetLocalControllerPosition(OVRInput.Controller.RTouch);
    }

    private void SetMeshRenderersVisible(bool visible)
    {
        if (meshObject == null) return;
        foreach (var r in meshObject.GetComponentsInChildren<MeshRenderer>(true))
            r.enabled = visible;
    }
#endif

    private void ToggleMeshVisibility()
    {
        var renderers = meshObject.GetComponentsInChildren<MeshRenderer>(true);
        if (renderers.Length == 0) return;
        bool next = !renderers[0].enabled;
        foreach (var r in renderers) r.enabled = next;
        Debug.Log($"[MeshHandler] Mesh visibility → {next}");
    }

    /// <summary>
    /// Expert side: sends RPC to show/hide SharedMesh on ALL clients (Worker passthrough + Expert screen).
    /// Call via FindAnyObjectByType&lt;MeshHandler&gt;().RequestSetMeshVisible(true/false) from ExpertUI2.
    /// </summary>
    public void RequestSetMeshVisible(bool visible)
    {
        photonView.RPC(nameof(RPC_SetMeshVisible), RpcTarget.All, visible);
    }

    [PunRPC]
    private void RPC_SetMeshVisible(bool visible)
    {
        if (meshObject == null) meshObject = GameObject.Find(meshObjectName);
        if (meshObject == null) return;
        foreach (var r in meshObject.GetComponentsInChildren<MeshRenderer>(true))
            r.enabled = visible;
        Debug.Log($"[MeshHandler] RPC_SetMeshVisible → {visible}");
    }

    [PunRPC]
    private void RPC_NotifyCalibComplete()
    {
        OnCalibCompleteNotified?.Invoke();
        Debug.Log("[MeshHandler] RPC_NotifyCalibComplete: dual-QR calibration complete.");
    }

    public void SendMeshTransform()
    {
        if (meshObject == null) return;
        Vector3    pos   = meshObject.transform.position;
        Quaternion rot   = meshObject.transform.rotation;
        Vector3    scale = meshObject.transform.localScale;
        Debug.Log($"[MeshHandler] SendMeshTransform pos={pos} rot={rot.eulerAngles} scale={scale}");
        photonView.RPC(nameof(RPC_ReceiveMeshTransform), RpcTarget.AllBuffered, pos, rot, scale);
    }

    /// <summary>
    /// Re-broadcast the calibrated mesh transform + calib-complete (+ markers) to the room.
    /// The Worker can finish dual-QR calibration BEFORE it joins the Photon room (the startup panel
    /// delays the join, and MRUK auto-detects the calib QRs meanwhile). A one-shot RPC sent while
    /// not in a room is lost — the Expert's SharedMesh then stays at its default and the Worker
    /// appears offset, calib never reflects, and the approve gate deadlocks. Call this on room join.
    /// </summary>
    public void RebroadcastCalibration()
    {
        if (!PhotonNetwork.InRoom || meshObject == null) return;
        if (IsDualQRMode && _dualCalibState != DualQRCalibState.Complete) return;  // not calibrated yet

        SendMeshTransform();
        photonView.RPC(nameof(RPC_NotifyCalibComplete), RpcTarget.AllBuffered);
        _qrManager?.ResyncAllMarkers();
        Debug.Log("[MeshHandler] RebroadcastCalibration: re-sent mesh transform + calib-complete on room join.");
    }

    [PunRPC]
    private void RPC_ReceiveMeshTransform(Vector3 pos, Quaternion rot, Vector3 scale)
    {
        if (meshObject == null) meshObject = GameObject.Find(meshObjectName);
        if (meshObject == null)
        {
            Debug.LogWarning($"[MeshHandler] RPC_ReceiveMeshTransform: '{meshObjectName}' not found in scene.");
            return;
        }
        Debug.Log($"[MeshHandler] RPC_ReceiveMeshTransform pos={pos} rot={rot.eulerAngles} scale={scale}");
        meshObject.transform.SetPositionAndRotation(pos, rot);
        meshObject.transform.localScale = scale;
    }

#if UNITY_ANDROID && !UNITY_EDITOR
    private void OnQRMarkerDetected(string markerId, Vector3 pos, Quaternion rot)
    {
        if (IsDualQRMode)
            HandleDualQRDetection(markerId, pos);
        else
            HandleSingleQRDetection(markerId, pos, rot);
    }

    private void HandleSingleQRDetection(string markerId, Vector3 pos, Quaternion rot)
    {
        if (_qrCalibrated) return;
        if (!markerId.StartsWith(calibrationQRPrefix)) return;

        // SharedMesh の yaw = QR yaw − GridOrigin の local yaw
        float anchorLocalYaw = calibrationAnchor != null ? calibrationAnchor.localEulerAngles.y : 0f;
        Quaternion newRot = Quaternion.Euler(0f, rot.eulerAngles.y - anchorLocalYaw, 0f);
        meshObject.transform.rotation = newRot;

        if (calibrationAnchor != null)
        {
            Vector3 anchorLocal = meshObject.transform.InverseTransformPoint(calibrationAnchor.position);
            meshObject.transform.position = pos - newRot * anchorLocal;
        }
        else
        {
            meshObject.transform.position = pos;
        }

        SendMeshTransform();
        _qrCalibrated = true;
        Debug.Log($"[MeshHandler] Single-QR calib: id='{markerId}' anchor={calibrationAnchor?.name ?? "none"} pos={pos} meshYaw={newRot.eulerAngles.y:F1}°");
    }

    private void HandleDualQRDetection(string markerId, Vector3 pos)
    {
        if (_dualCalibState == DualQRCalibState.Complete) return;

        if (markerId == calibrationQRIdA)
        {
            _detectedA = pos;
            Debug.Log($"[MeshHandler] Dual-QR: QR-A detected at {pos}");
        }
        else if (markerId == calibrationQRIdB)
        {
            _detectedB = pos;
            Debug.Log($"[MeshHandler] Dual-QR: QR-B detected at {pos}");
        }
        else return;

        // Advance state machine for HUD guidance: one QR seen but not both → instruct on the other.
        // Uses XOR so B-before-A also advances (avoids HUD staying on "NeedsA" when B is detected first).
        if (_dualCalibState == DualQRCalibState.NeedsA && (_detectedA.HasValue != _detectedB.HasValue))
        {
            _dualCalibState = DualQRCalibState.NeedsB;
            OnDualQRCalibStep?.Invoke(DualQRCalibState.NeedsB);
        }

        if (_detectedA.HasValue && _detectedB.HasValue)
        {
            if (meshObject == null) return;
            // Indicators must be direct children of SharedMesh (uniform scale assumed = photogrammetry export).
            // InverseTransformPoint is used (vs localPosition) to correctly handle any nesting depth.
            Vector3 aLocal = meshObject.transform.InverseTransformPoint(indicatorA.position);
            Vector3 bLocal = meshObject.transform.InverseTransformPoint(indicatorB.position);

            var (newPos, newRot) = DualQRCalibration.ComputePose(
                aLocal, bLocal, _detectedA.Value, _detectedB.Value);

            meshObject.transform.SetPositionAndRotation(newPos, newRot);
            SendMeshTransform();
            _dualCalibState = DualQRCalibState.Complete;  // guard must be set before ResyncAllMarkers
            OnDualQRCalibStep?.Invoke(DualQRCalibState.Complete);
            // AllBuffered (not All): the Expert may join AFTER the Worker calibrates (e.g. Editor
            // started later, or reconnect). The mesh transform is already AllBuffered
            // (RPC_ReceiveMeshTransform), so without buffering this notify the Expert would have a
            // correctly-placed mesh but never flip _calibDone — the Setup UI/approve gate would show
            // calibration as incomplete. Replaying is idempotent (just re-sets _calibDone).
            photonView.RPC(nameof(RPC_NotifyCalibComplete), RpcTarget.AllBuffered);
            _qrManager?.StopPeriodicBroadcast();  // 較正完了 → ポーリング不要
            _qrManager?.ResyncAllMarkers();  // 較正前に検出済みのQRを新フレームで再送
            Debug.Log($"[MeshHandler] Dual-QR complete: pos={newPos} yaw={newRot.eulerAngles.y:F1}°");
        }
    }

    /// <summary>
    /// Resets the dual-QR calibration state so the Worker can re-scan both QR codes.
    /// Call via RPC from Expert if visual verification reveals bad alignment.
    /// Has no effect in single-QR (legacy) mode.
    /// </summary>
    public void ResetDualCalibration()
    {
        if (!IsDualQRMode) return;
        _dualCalibState = DualQRCalibState.NeedsA;
        _detectedA      = null;
        _detectedB      = null;
        OnDualQRCalibStep?.Invoke(DualQRCalibState.NeedsA);
        _qrManager?.StartPeriodicBroadcast();  // リセット → ポーリング再開
        Debug.Log("[MeshHandler] Dual-QR calibration reset — Worker can re-scan QR-A.");
    }

    private void ApplyBakedCollisionMeshes(GameObject target)
    {
        // Baker iterates MeshFilters; colliders were just added in the same order by
        // OptimizeMeshPerformance, so indices align.
        var filters = target.GetComponentsInChildren<MeshFilter>(true);
        int applied = 0;
        for (int i = 0; i < filters.Length && i < bakedCollisionMeshes.Length; i++)
        {
            if (bakedCollisionMeshes[i] == null) continue;
            var col = filters[i].GetComponent<MeshCollider>();
            if (col != null)
            {
                col.sharedMesh = bakedCollisionMeshes[i];
                applied++;
            }
        }
        Debug.Log($"[MeshHandler] Applied {applied} baked collision mesh(es).");
    }

#endif
}
