using UnityEngine;
using Photon.Pun;

public class MeshHandler : MonoBehaviourPun
{
    [Header("Scene内の事前配置メッシュのオブジェクト名")]
    [SerializeField] private string meshObjectName = "SharedMesh";

    [Header("Calibration Settings")]
    [SerializeField] private float moveSpeed = 1.0f;
    [SerializeField] private float rotateSpeed = 45f;

    [Header("Android Collision Mesh Simplification")]
    [Tooltip("Pre-baked simplified meshes generated by CoGaze → Bake Collision Mesh. Assign to skip runtime simplification.")]
    [SerializeField] private Mesh[] bakedCollisionMeshes;
    [Tooltip("QEM quality for Bake (0=最小ポリゴン, 1=原型維持). 0.02〜0.05 が衝突判定用として推奨。")]
    [Range(0f, 1f)]
    [SerializeField] private float collisionMeshQuality = 0.03f;

    [Header("QR Calibration")]
    [Tooltip("QRコードのmarkerId がこの文字列で始まる場合、メッシュの初期位置として自動セットする。例: 'calib'")]
    [SerializeField] private string calibrationQRPrefix = "calib";

    private GameObject meshObject;
    private bool isCalibrating = false;
    private bool _qrCalibrated = false;
    private QRSpatialManager _qrManager;

    /// <summary>Fired on the Worker when calibration mode is toggled on (true) or off (false).</summary>
    public event System.Action<bool> OnCalibrationChanged;

    /// <summary>Fired on the Worker when calibration is confirmed (A button).</summary>
    public event System.Action OnCalibrationConfirmed;

    private void Start()
    {
        meshObject = GameObject.Find(meshObjectName);
        if (meshObject == null)
        {
            Debug.LogWarning($"[MeshHandler] Pre-placed mesh '{meshObjectName}' not found in scene.");
            return;
        }
        OptimizeMeshPerformance(meshObject);
#if UNITY_ANDROID && !UNITY_EDITOR
        // Default hidden on Quest — photogrammetry mesh far exceeds Quest GPU budget.
        // Use X button to show during calibration, then hide again.
        foreach (var r in meshObject.GetComponentsInChildren<MeshRenderer>(true))
            r.enabled = false;

        _qrManager = FindAnyObjectByType<QRSpatialManager>();
        if (_qrManager != null)
            _qrManager.OnMarkerDetected += OnQRMarkerDetected;
        else
            Debug.LogWarning("[MeshHandler] QRSpatialManager not found — QR calibration disabled.");
#endif
    }

    private void OnDestroy()
    {
#if UNITY_ANDROID && !UNITY_EDITOR
        if (_qrManager != null)
            _qrManager.OnMarkerDetected -= OnQRMarkerDetected;
#endif
    }

    private void OptimizeMeshPerformance(GameObject target)
    {
        foreach (var r in target.GetComponentsInChildren<MeshRenderer>(true))
        {
            r.shadowCastingMode = UnityEngine.Rendering.ShadowCastingMode.Off;
            r.receiveShadows = false;
        }

        // MeshColliders are required on Quest — GazeVisualizer raycasts against them to place
        // the Circle marker. On Android we replace each collider mesh with a vertex-clustered
        // simplification so bake time and raycast cost stay within Quest's budget.
        int added = 0;
        foreach (var f in target.GetComponentsInChildren<MeshFilter>(true))
        {
            if (f.GetComponent<Collider>() == null)
            {
                f.gameObject.AddComponent<MeshCollider>();
                added++;
            }
        }
        if (added > 0) Debug.Log($"[MeshHandler] Added {added} MeshColliders.");

#if UNITY_ANDROID && !UNITY_EDITOR
        if (bakedCollisionMeshes != null && bakedCollisionMeshes.Length > 0)
            ApplyBakedCollisionMeshes(target);
        else
        {
            Debug.LogWarning("[MeshHandler] No baked collision mesh assigned. Run CoGaze → Bake Collision Mesh before building to Quest.");
        }
#endif

        var colliders = target.GetComponentsInChildren<MeshCollider>(true);
        if (colliders.Length > 0 && target.GetComponent<Rigidbody>() == null)
        {
            var rb = target.AddComponent<Rigidbody>();
            rb.isKinematic = true;
            rb.useGravity = false;
        }
    }

    private void Update()
    {
        if (!photonView.IsMine || meshObject == null) return;
#if UNITY_ANDROID
        UpdateCalibration();
#endif
    }

#if UNITY_ANDROID
    // Analog axis threshold — handles Touch Plus axis inconsistency on MQ3 / MQ3S.
    private const float TriggerThreshold = 0.7f;
    private const float StickDeadzone    = 0.15f;

    // Grip rising-edge state for toggle detection
    private bool _gripWasDown = false;

    private void UpdateCalibration()
    {
        // X button (left controller) — toggle mesh visibility
        if (OVRInput.GetDown(OVRInput.Button.One, OVRInput.Controller.LTouch))
            ToggleMeshVisibility();

        // Right grip — TOGGLE calibration mode (press once = in, press again = out)
        bool gripDown = OVRInput.Get(OVRInput.Axis1D.PrimaryHandTrigger, OVRInput.Controller.RTouch) > TriggerThreshold;
        if (gripDown && !_gripWasDown)
        {
            isCalibrating = !isCalibrating;
            OnCalibrationChanged?.Invoke(isCalibrating);
            Debug.Log($"[MeshHandler] Calibration {(isCalibrating ? "ON" : "OFF")}.");
        }
        _gripWasDown = gripDown;

        if (!isCalibrating) return;

        // ── Scheme D ──────────────────────────────────────────────────────────
        // Stick alone      → XZ translation (relative to HMD facing)
        // Trigger + stick Y → height (Y-axis)
        // Trigger + stick X → Y-axis rotation
        // A button          → confirm & send
        // ─────────────────────────────────────────────────────────────────────

        Vector2 stick       = OVRInput.Get(OVRInput.Axis2D.PrimaryThumbstick, OVRInput.Controller.RTouch);
        bool    indexTrigger = OVRInput.Get(OVRInput.Axis1D.PrimaryIndexTrigger, OVRInput.Controller.RTouch) > TriggerThreshold;

        if (indexTrigger)
        {
            if (Mathf.Abs(stick.y) > StickDeadzone)
                meshObject.transform.position += Vector3.up * stick.y * moveSpeed * Time.deltaTime;

            if (Mathf.Abs(stick.x) > StickDeadzone)
                meshObject.transform.Rotate(Vector3.up, stick.x * rotateSpeed * Time.deltaTime, Space.World);
        }
        else if (stick.sqrMagnitude > StickDeadzone * StickDeadzone)
        {
            Transform hmd = Camera.main != null ? Camera.main.transform : transform;
            Vector3 fwd = Vector3.ProjectOnPlane(hmd.forward, Vector3.up).normalized;
            Vector3 rgt = Vector3.ProjectOnPlane(hmd.right,   Vector3.up).normalized;
            meshObject.transform.position += (fwd * stick.y + rgt * stick.x) * moveSpeed * Time.deltaTime;
        }

        // A button → confirm & send
        if (OVRInput.GetDown(OVRInput.Button.One, OVRInput.Controller.RTouch))
        {
            SendMeshTransform();
            OnCalibrationConfirmed?.Invoke();
            OVRInput.SetControllerVibration(0.5f, 0.8f, OVRInput.Controller.RTouch);
            StartCoroutine(StopVibration(0.2f));
            Debug.Log("[MeshHandler] Calibration confirmed and sent.");
        }
    }

    private System.Collections.IEnumerator StopVibration(float delay)
    {
        yield return new WaitForSeconds(delay);
        OVRInput.SetControllerVibration(0f, 0f, OVRInput.Controller.RTouch);
    }
#endif

    private void ToggleMeshVisibility()
    {
        var renderers = meshObject.GetComponentsInChildren<MeshRenderer>(true);
        if (renderers.Length == 0) return;
        bool next = !renderers[0].enabled;
        foreach (var r in renderers) r.enabled = next;
        Debug.Log($"[MeshHandler] Mesh visibility → {next}");
    }

    public void SendMeshTransform()
    {
        if (meshObject == null) return;
        Vector3    pos   = meshObject.transform.position;
        Quaternion rot   = meshObject.transform.rotation;
        Vector3    scale = meshObject.transform.localScale;
        Debug.Log($"[MeshHandler] SendMeshTransform pos={pos} rot={rot.eulerAngles} scale={scale}");
        photonView.RPC(nameof(RPC_ReceiveMeshTransform), RpcTarget.AllBuffered, pos, rot, scale);
    }

    [PunRPC]
    private void RPC_ReceiveMeshTransform(Vector3 pos, Quaternion rot, Vector3 scale)
    {
        if (meshObject == null) meshObject = GameObject.Find(meshObjectName);
        if (meshObject == null)
        {
            Debug.LogWarning($"[MeshHandler] RPC_ReceiveMeshTransform: '{meshObjectName}' not found in scene.");
            return;
        }
        Debug.Log($"[MeshHandler] RPC_ReceiveMeshTransform pos={pos} rot={rot.eulerAngles} scale={scale}");
        meshObject.transform.SetPositionAndRotation(pos, rot);
        meshObject.transform.localScale = scale;
    }

#if UNITY_ANDROID && !UNITY_EDITOR
    private void OnQRMarkerDetected(string markerId, Vector3 pos, Quaternion rot)
    {
        if (_qrCalibrated) return;
        if (!markerId.StartsWith(calibrationQRPrefix)) return;

        // QRの位置をそのまま使い、Y軸回転のみ採用してメッシュを起こしたまま保つ
        meshObject.transform.position = pos;
        meshObject.transform.rotation = Quaternion.Euler(0f, rot.eulerAngles.y, 0f);

        SendMeshTransform();
        _qrCalibrated = true;
        Debug.Log($"[MeshHandler] QR calibration applied: id='{markerId}' pos={pos} yaw={rot.eulerAngles.y:F1}°");
    }

    private void ApplyBakedCollisionMeshes(GameObject target)
    {
        // Baker iterates MeshFilters; colliders were just added in the same order by
        // OptimizeMeshPerformance, so indices align.
        var filters = target.GetComponentsInChildren<MeshFilter>(true);
        int applied = 0;
        for (int i = 0; i < filters.Length && i < bakedCollisionMeshes.Length; i++)
        {
            if (bakedCollisionMeshes[i] == null) continue;
            var col = filters[i].GetComponent<MeshCollider>();
            if (col != null)
            {
                col.sharedMesh = bakedCollisionMeshes[i];
                applied++;
            }
        }
        Debug.Log($"[MeshHandler] Applied {applied} baked collision mesh(es).");
    }

#endif
}
